export const SELECTORS = {
  common: {
  },
  basicInputs: {
    formWrapper: "#form-elements-wrapper",
    form: "#ajax-submitted-form",
    formHeading: "h2",
    requiredToggle: "#toggle-required",
    buttonInput: "#button-input",
    checkboxInput: "#checkbox-input",
    radioGroup: "#radio-input",
    radio1: "#radio-input-1",
    radio2: "#radio-input-2",
    hiddenInput: "#hidden-input",
    validateButton: "#validate-inputs",
    validateSendButton: "#validate-send-inputs",
    sendButton: "#send-inputs",
    statusMessage: "#statusmessage",
    formResults: "#form-results",
  },
  textInputs: {
    formWrapper: "#form-elements-wrapper",
    form: "#ajax-submitted-form",
    formHeading: "h2",
    requiredToggle: "#toggle-required",
    validationToggle: "#toggle-validation",
    textInput: "#text-input",
    textInputValidation: "#text-input-validation",
    searchInput: "#search-input",
    searchInputValidation: "#search-input-validation",
    passwordInput: "#password-input",
    passwordInputValidation: "#password-input-validation",
    emailInput: "#email-input",
    urlInput: "#url-input",
    telInput: "#tel-input",
    telInputValidation: "#tel-input-validation",
    textDefaultInput: "#text-default-input",
    textDefaultInputValidation: "#text-default-input-validation",
    validateButton: "#validate-inputs",
    validateSendButton: "#validate-send-inputs",
    sendButton: "#send-inputs",
    statusMessage: "#statusmessage",
    formResults: "#form-results",
  },
} as const;
